language: python
python:
  - "2.6"
  - "2.7"
  - "3.3"
env:
  - DJANGO=1.4
  - DJANGO=1.5
install:
  - pip install -q Django==$DJANGO --use-mirrors
  - pip install -q django-jsonfield==0.8.12
  - pip install -q mock --use-mirrors
  - pip install -q django-nose --use-mirrors
  - pip install -q pylint --use-mirrors
  - pip install -q pinax.checkers --use-mirrors
  - pip install -e . --use-mirrors
before_script:
  - "pylint --rcfile=.pylintrc payments"
script:
  - python runtests.py
matrix:
  exclude:
    - env: DJANGO=1.4
    - python: 3.3