site_name: Pinax Stripe
pages:
- Home: index.md
- User Guide:
    - Getting Started: user-guide/getting-started.md
    - Settings & Configuration: user-guide/settings.md
    - eCommerce: user-guide/ecommerce.md
    - Upgrading from DSP: user-guide/upgrading.md
- Reference:
    - Actions: reference/actions.md
    - Management Commands: reference/commands.md
    - Signals: reference/signals.md
    - Webhooks: reference/webhooks.md
- About:
    - License: about/license.md
    - History: about/history.md
    - Release Notes: about/release-notes.md
theme: readthedocs
markdown_extensions:
    - admonition
